### ISSUE TITLE
Layout Issues

### ISSUE THREAD

**Issue by iamabhishek229313** [iamabhishek229313/flutter_twitter#17]
There are many layout issues in the following screens.
LoginScreen(),
StartScreen(),
SingupScreen(),
HomeDrawer() ,

Use responsive desgin .
Use of mainAxisAlignment and crossAxisAlignment should be there.

**Comment by sudhansubhushanmishra** [comment]
Okay. Could you suggest a way to replace the sizedboxes in the signup screen with column alignment, or should i just base the height from MediaQuery in those boxes? Will resume active work after PS exam mostly, and am pulling changes from master into dev_sbm

**Comment by iamabhishek229313** [comment]
This is fixed . Thanks to our nearly 1 hrs live code.

**Comment by iamabhishek229313** [comment]
Closing that issue .
