### ISSUE TITLE
The Buttom Button not getting over the keyboard.

### ISSUE THREAD

**Issue by iamabhishek229313** [iamabhishek229313/flutter_twitter#22]
**How to align that Bottom_button**

![bottom_button](https://user-images.githubusercontent.com/44896537/85019223-1be8c980-b18c-11ea-81df-40e7a40499be.JPG)

**over that Keyboard**

![keyboard](https://user-images.githubusercontent.com/44896537/85019230-1d19f680-b18c-11ea-94d2-aa57782fb5ff.JPG)

**Comment by sudhansubhushanmishra** [comment]
![image](https://user-images.githubusercontent.com/13695177/85040233-35970a80-b1a6-11ea-8f72-00094f055ca6.png)
I don't know what I did but it resulted in this.

**Comment by sudhansubhushanmishra** [comment]
This doesn't seem to work on the Login page though

**Comment by sudhansubhushanmishra** [comment]
Found a fix sort of by using `MediaQuery`

![image](https://user-images.githubusercontent.com/13695177/85200895-bfff7b80-b318-11ea-9949-02c6c85277ae.png)
